GET http://localhost:8080/api/users
Content-Type: application/json

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Maria Perez",
  "age": 30,
  "email": "maria@gmail.com",
  "password": "123456"
}

###

PUT http://localhost:8080/api/users/67183b3f00ea1ec265096085
Content-Type: application/json

{
  "name": "John Doe2 ",
  "age": 33,
  "email": "jhon2@doe.com"  
}

###