GET http://localhost:8080/api/users
Content-Type: application/json

###

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "age": 30,
  "email": "jhon@doe.com"
}

###

GET http://localhost:8080/api/users/67171a649c81d1ff83259e5a
Content-Type: application/json

###